on:
  pull_request:
    branches: [master]
  workflow_call:
  
name: test-app

jobs:
  test-app:
    name: test-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
          use-public-rspm: true

      # Connect does not like `renv`'s `./.Rprofile`
      # Removing from deployment as Connect listens to the `./manifest.json` file
      - name: Remove `.Rprofile`
        shell: bash
        run: |
          rm .Rprofile

      - uses: r-lib/actions/setup-renv@v2 # use our renv.lock

      - name: Test app
        uses: rstudio/shinytest2/actions/test-app@main